services:
  pulsar:
    image: apachepulsar/pulsar:4.0.6
    command: bin/pulsar standalone
    environment:
      PULSAR_MEM: -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g
    ports:
      - 6650:6650
      - 8085:8080
    restart: unless-stopped
    networks:
      - app-net

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.3.0
    ports:
      - 9527:9527
      - 7750:7750
    depends_on:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    networks:
      - app-net

networks:
  app-net:
    external: true