services:
  service-a:
    build:
      context: ./service-a
    image: service-a:latest
    container_name: service-a
    ports:
      - "8081:8080"
    environment:
      SERVER_PORT: 8080
    networks:
      - app-net

  service-b:
    build:
      context: ./service-b
    image: service-b:latest
    container_name: service-b
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
    networks:
      - app-net

  orchestrator:
    build:
      context: ./orchestrator
    image: orchestrator:latest
    container_name: orchestrator
    ports:
      - "8080:8080"   # host port 8080 -> container port 80
    environment:
      SERVER_PORT: 8080
      SERVICE_A_URL: http://service-a:8080/processA
      SERVICE_B_URL: http://service-b:8080/processB
      SERVICE_A_COMPENSATE_URL: http://service-a:8080/compensateA
      SERVICE_B_COMPENSATE_URL: http://service-b:8080/compensateB
      JAVA_TOOL_OPTIONS: "--add-exports=java.base/sun.net=ALL-UNNAMED"
    depends_on:
      - service-a
      - service-b
    networks:
      - app-net

networks:
  app-net:
    external: true
    #driver: bridge
